TrajectoryPlannerROS:
  max_vel_x: 2.2352
  min_vel_x: 1.0
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -2.0
  
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

  global_frame_id: odom


  holonomic_robot: false