
footprint: [[0.4725,-0.365], [0.4725,0.365], [-0.4725,0.365], [-0.4725,-0.365]]

#robot_radius: ir_of_robot
inflation_radius: 0.25

plugins:
  - {name: obstacles_3d,      type: "costmap_2d::VoxelLayer"}
  - {name: obstacles_2d,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

obstacles_3d:
  enabled:                true
  origin_z:               0.0    # meters
  z_resolution:           0.1
  z_voxels:               10
  mark_threshold:         4
  unknown_threshold:      10
  combination_method:     1      # 1=max, 0=override
  track_unknown_space:    true   # default space is unknown
  observation_sources: lidar
  
  depth_cam:
    data_type: PointCloud2
    topic: /zed/zed_node/point_cloud/cloud_registered
    sensor_frame: camera_depth_link
    # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
    # observation_persistence: 0.0
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0

  lidar:
    data_type: PointCloud2
    topic: /velodyne_points
    sensor_frame: velodyne
    # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
    # observation_persistence: 0.0
    obstacle_range:         5.0    # meters
    raytrace_range:         20
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0
  
