local_costmap:
  global_frame: map # For some reason, this should be in the map frame
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 4.0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.1